version: "3"

services:
  api:
    image: application-snake
    build: .
    networks:
      - backend
    ports:
      - "3001:3001"

  web-cli:
    image: application-snake
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge