version: "3"

volumes:
  peer0.org1.ap.com:

networks:
  apnet:

services:
  peer0.org1.ap.com:
    networks:
      - apnet
    container_name: peer0.org1.ap.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    volumes:
      - ../crypto-material/peerOrganizations/org1.ap.com/peers/peer0.org1.ap.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-material/peerOrganizations/org1.ap.com/peers/peer0.org1.ap.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org1.ap.com:/var/hyperledger/production
    environment:
      # Generic peer variables
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt 
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key 
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt 
      # Specific peer variables
      - CORE_PEER_ID=peer0.org1.ap.com
      - CORE_PEER_ADDRESS=peer0.org1.ap.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.ap.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.ap.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051